#!/bin/sh
# svscan starts this automatically as indieauth's log service: supervise
# pipes the main run script's stdout/stderr into this one's stdin.

exec setuidgid indieauth-log multilog t /var/log/indieauth
